Drop TABLE IF EXISTS pastes;

CREATE TABLE IF NOT EXISTS pastes (
  id TEXT PRIMARY KEY,
  slug TEXT UNIQUE NOT NULL,
  content BLOB NOT NULL,
  content_type TEXT NOT NULL,
  expires_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS slug_idx ON pastes (slug);