name = "pb"
compatibility_date = "2023-12-01"
assets = { directory = "public" }

[vars]
HOST = "p.kururin.cc"

[[d1_databases]]
binding = "DB"
database_name = "pb"
database_id = "5aebacbf-9665-4f02-9558-8116ae8d8a36"

[env.dev.triggers]
crons = ["0 0 */1 * *"]
